# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Plinko Blaster' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Plinko Blaster

  pod 'EFCountingLabel'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'DeviceKit', '~> 2.0'

end
